#!/bin/bash

# The following documentation was used as a basis for configuration of the TLSRoute and 
# TLS passthrough to the Nginx server. Modifications were made as istio is deployed in
# ambient mode and not with a sidecar.
# https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/

# Step 1 - Deploys and configures the following:
#            a) minikube, minikube addons (dashboard, metrics-server);
#            b) configures encryption for etcd storage
#            c) installs istio in ambient mode
#            d) installs kubernetes gateway API CRDs
#            e) Installs and configures nginx with TLS passthrough to the nginx server.

# This learning prototype was developed and tested using the following:
#   a) Ubuntu             - 20.04.6 LTS
#   b) Minikube           - 1.34.0
#   c) Kubernetes         - 1.31.0
#   d) Docker             - 27.2.0
#   d) Cert-manager       - 1.15.3
#   e) Istio              - 1.23.2
#   f) Metallb            - 0.9.6
#   g) Kubernetes Gateway - 1.1.0
#   h) Nginx server       - 
#   i) Machine config - Processor - Intel® Core™ i7-7700K CPU @ 4.20GHz × 8 
#                       Memory    - 64 GB
#            
# Open terminal 1
# Delete prior minikube ( if used and configured prior)
minikube delete

# Start minikube - configure the settings to your requirements and hardware
# Note - normally I use kvm2 as the vm-driver. However istio cni in ambient mode does not
# currently work with kvm2 due to cni incompatibility. The work around is to use the 
# docker vm-driver.
minikube start --cpus 4 --memory 12288 --vm-driver docker --cni kindnet --disk-size 100g

# Addons
minikube addons enable dashboard

# Deploy the addon loadbalancer metallb
minikube addons enable metallb

# Configure loadbalancer ip address range within the same range as the minikube ip
# The configuration is a start ip ( ie. 192.168.39.40 ) and an end ip that makes a 
# range of 10 ip addresses. The range should not overlap the minikube ip
minikube ip
minikube addons configure metallb
  -- Enter Load Balancer Start IP: 
  -- Enter Load Balancer End IP:

# Start dashboard
minikube dashboard

# Open up a new (2nd) terminal
# Install the Kubernetes Gateway API CRDs (experimental also includes standard)
#kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/experimental-install.yaml

# Install istio in ambient mode
istioctl install --set values.pilot.env.PILOT_ENABLE_ALPHA_GATEWAY_API=true --set profile=ambient --skip-confirmation

# Deploy app
PROTODIR=/media/tim/ExtraDrive1/Projects/learn-03-basic-gateway-api/Proto-05

# Create root cert and key
mkdir -p $PROTODIR/certs
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -subj '/O=example Inc./CN=example.com' -keyout $PROTODIR/certs/example.com.key -out $PROTODIR/certs/example.com.crt

# Create nginx cert and key
openssl req -out $PROTODIR/certs/nginx.example.com.csr -newkey rsa:2048 -nodes -keyout $PROTODIR/certs/nginx.example.com.key -subj "/CN=nginx.example.com/O=an organization"
openssl x509 -req -sha256 -days 365 -CA $PROTODIR/certs/example.com.crt -CAkey $PROTODIR/certs/example.com.key -set_serial 0 -in $PROTODIR/certs/nginx.example.com.csr -out $PROTODIR/certs/nginx.example.com.crt

# Create a secret with the certs and key
kubectl create secret tls nginx-server-certs \
  --key=$PROTODIR/certs/nginx.example.com.key \
  --cert=$PROTODIR/certs/nginx.example.com.crt

# Create a ConfigMp to hold the nginx conf
kubectl create configmap nginx-configmap --from-file=nginx.conf=$PROTODIR/conf/nginx.conf

kubectl apply -f $PROTODIR/kube/nginx.yaml

# Review and wait until Ready
kubectl get pods

# Deploy nginx-gateway and route
kubectl apply -f $PROTODIR/kube/nginx-gateway.yaml

# Check the status - wait until the Address is available and PROGRAMMED=True
kubectl get gateway
kubectl wait --for=condition=programmed gtw nginx-gateway

# Add the app to the service mesh by labeling the (default) namespace.
# Note - this automatically starts mTls between the pods 
kubectl label namespace default istio.io/dataplane-mode=ambient

export INGRESS_HOST=$(kubectl get gtw nginx-gateway -o jsonpath='{.status.addresses[0].value}')
export SECURE_INGRESS_PORT=$(kubectl get gtw nginx-gateway -o jsonpath='{.spec.listeners[?(@.name=="https")].port}')

echo "INGRESS_HOST = $INGRESS_HOST"
echo "SECURE_INGRESS_PORT = $SECURE_INGRESS_PORT"

# Test https
curl -v --resolve "nginx.example.com:$SECURE_INGRESS_PORT:$INGRESS_HOST" --cacert $PROTODIR/certs/example.com.crt "https://nginx.example.com:$SECURE_INGRESS_PORT"

