---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mango-tls-cert-issuer
spec:
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: mango.example.com
  secretName: mango-credential
  issuerRef:
    name: root-tls-cert-issuer
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mango-tls-cert-issuer
spec:
  ca:
    secretName: mango-credential




